# Generated by Django 5.1.6 on 2025-03-13 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_asignacionproduct_productassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_prototype_brand', to='inventory.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='tipo',
            field=models.CharField(choices=[('A', 'PERIFERICOS'), ('B', 'EQUIPOS DE OFICINA'), ('C', 'EQUIPOS DE COMPUTO'), ('D', 'OTROS')], max_length=1, null=True, verbose_name='Tipo de marca'),
        ),
    ]
